blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/kosovatools/kosovatools.org/discussions
    about: "Use GitHub Discussions for open-ended questions and community support."
