name: Build & Deploy Next.js Static (pnpm)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install stats dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r packages/stats/requirements.txt

      - name: Refresh KAS datasets
        run: python packages/stats/scripts/fetch_kas.py --out packages/stats/data --months 36

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Fetch customs dataset
        if: github.event_name != 'pull_request'
        run: pnpm --filter @workspace/customs-data fetch-tarrifs
        env:
          CUSTOMS_DATA_SOURCE_URL: ${{ secrets.CUSTOMS_DATA_SOURCE_URL }}

      - name: Trim customs dataset
        if: github.event_name != 'pull_request'
        run: pnpm --filter @workspace/customs-data trim-tarrifs

      - name: Build Turborepo packages
        run: pnpm turbo run build --filter=web...
        env:
          NEXT_TELEMETRY_DISABLED: "1"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/out

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-preview:
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: "preview/pr-${{ github.event.pull_request.number }}"
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy preview to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true
